DROP TABLE IF EXISTS CNES_ATIVO;
DROP SEQUENCE IF EXISTS SEQ_CNES;
CREATE TABLE CNES_ATIVO AS SELECT * FROM CSVREAD('classpath:cnes_ativo.csv');
CREATE SEQUENCE SEQ_CNES INCREMENT BY 1 START WITH 9303597 NOCACHE NOCYCLE;